layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: willem-van-beek-b93435174/
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://iatcontrol.nl/
  # youtube: your_username

topics:
topics:
  - name: Angular
    web_url: https://github.com/topics/angular
    image_url: https://images.seeklogo.com/logo-png/33/2/angular-logo-png_seeklogo-331629.png

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
  
  - name: .NET Core
    web_url: https://github.com/topics/dotnet-core
    image_url: https://upload.wikimedia.org/wikipedia/commons/e/ee/.NET_Core_Logo.svg
    
  - name: C#
    web_url: https://github.com/topics/csharp
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/csharp/csharp.png
    
  - name: IoT
    web_url: https://github.com/topics/iot
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/iot/iot.png
    
  - name: Industrial Automation
    web_url: https://github.com/topics/industrial-automation
    
  - name: Real-time Data Processing
    web_url: https://github.com/topics/real-time
    
  - name: SignalR
    web_url: https://github.com/topics/signalr
    image_url: https://avatars.githubusercontent.com/u/6154722?s=200&v=4
    
  - name: Entity Framework
    web_url: https://github.com/topics/entity-framework
    
  - name: Background Services
    web_url: https://github.com/topics/background-jobs
    
  - name: Clean Architecture
    web_url: https://github.com/topics/clean-architecture
    
  - name: CQRS
    web_url: https://github.com/topics/cqrs
    
  - name: Manufacturing
    web_url: https://github.com/topics/manufacturing
